### ISSUE TITLE
get Baltimore group info as well

### ISSUE THREAD

**Issue by Aciole-David** [AliYoussef96/BioVirusHost#1]
Hello there,

as the title says, is it possible to fetch the Baltimore group information too, like we do with the Virus-Host DB web-version?
![image](https://user-images.githubusercontent.com/29051553/122108536-b0632780-cdf2-11eb-98b1-d2a9c463df1a.png)

Thanks,
David

**Comment by AliYoussef96** [comment]
Hi, @Aciole-David

Sorry for taking too much time.

Sure, you can get Baltimore group information too.

```python
for i in more_info("1573458", "A.N.Other@example.com"):
    print(i.iloc[2])
```

This will return a data frame containing the virus information; selecting the third row **i.iloc[2]** will get only the Baltimore group information.
